version: '3.8'

services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"

  receiver-service:
    build: ./receiver-service
    container_name: receiver-service
    depends_on:
      - mongo
      - redis
    environment:
      - MONGO_URI=mongodb://mongo:27017/receiver_db
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - "5000:5000"

  listener-service:
    build: ./listener-service
    container_name: listener-service
    depends_on:
      - mongo
      - redis
      - receiver-service
    environment:
      - MONGO_URI=mongodb://mongo:27017/receiver_db
      - REDIS_HOST=redis
      - REDIS_PORT=6379
